"""Built-in original cast and a hand-authored demo story.

The demo plan below was written by hand for this repository to exercise the
full pipeline without paid services. It is labelled ``source: hand_authored_demo``
everywhere it appears and is not presented as AI output or as research-driven.
"""
import copy

CHARACTERS = [
    {
        'id': 'ch_bloxy',
        'name': 'Bloxy',
        'bible': {
            'summary': 'Over-confident but kind-hearted obby runner who always takes the hard way first.',
            'personality': 'Brave, impulsive, quick to panic, quicker to laugh at themself.',
            'scale': 1.0,
            'palette': {'skin': '#F2C14E', 'top': '#18A999', 'top_trim': '#F4F1DE', 'pants': '#23325C',
                        'shoes': '#E2504C', 'hair': '#5B3A21', 'eyes': '#16161D', 'brows': '#3B2615',
                        'mouth': '#5B1A1A', 'badge': '#FFD23F'},
            'costume': {'top': 'hoodie', 'hair': 'messy_block', 'hat': None, 'badge': 'star'},
            'visual_rules': ['Teal hoodie with cream drawstring trim is always worn',
                             'Yellow star badge on the left chest', 'Messy brown block hair, no hat',
                             'Navy trousers and red trainers'],
        },
        'voice': {'openai_voice': 'verse',
                  'openai_instructions': 'Young, bright, energetic adventurer. Expressive, natural, not cartoonish.',
                  'elevenlabs_voice_id': '', 'local_test_voice': 'kal16', 'pitch_semitones': 0,
                  'piper_speaker': 60, 'rights_note': 'Piper LibriTTS model (CC BY 4.0) / provider catalogue voices'},
    },
    {
        'id': 'ch_pip',
        'name': 'Pip',
        'bible': {
            'summary': 'Calm, slightly smug best friend who always knows the shortcut.',
            'personality': 'Dry humour, loyal, enjoys Bloxy\'s chaos a little too much.',
            'scale': 0.9,
            'palette': {'skin': '#E9B48A', 'top': '#7B5CD6', 'top_trim': '#2E2A47', 'pants': '#3B7D4F',
                        'shoes': '#F4F1DE', 'hair': '#1F1A17', 'eyes': '#16161D', 'brows': '#1F1A17',
                        'mouth': '#5B1A1A', 'badge': '#FF8C42', 'hat': '#FF8C42'},
            'costume': {'top': 'tee', 'hair': 'short_block', 'hat': 'cap', 'badge': None},
            'visual_rules': ['Orange cap, brim forward', 'Purple T-shirt', 'Green trousers', 'Cream trainers'],
        },
        'voice': {'openai_voice': 'sage',
                  'openai_instructions': 'Calm, dry, gently teasing friend. Natural conversational timing.',
                  'elevenlabs_voice_id': '', 'local_test_voice': 'slt', 'pitch_semitones': 0,
                  'piper_speaker': 288, 'rights_note': 'Piper LibriTTS model (CC BY 4.0) / provider catalogue voices'},
    },
]


def _k(t, **pose):
    pose['t'] = t
    return pose


LAST_PLATFORM = {
    'source': 'hand_authored_demo',
    'title': 'The Missing Platform',
    'logline': 'Bloxy makes a heroic leap across the clouds, only to learn the exit was behind them all along.',
    'duration_s': 30.0,
    'story': {
        'premise': 'An obby runner finds the next platform missing.',
        'conflict': 'The gap looks far too wide to jump.',
        'stakes': 'Falling means restarting the whole obby.',
        'reveal': 'The exit door was right behind them the entire time.',
        'ending': 'Bloxy facepalms; Pip asks "Again?", implying it happens every time.',
        'ending_type': 'twist',
    },
    'hook': {'text': 'Bloxy reaches the edge and the next platform is gone.',
             'question': 'How will Bloxy cross the gap?', 't_end': 3.0},
    'payoff': {'text': 'Bloxy never needed to cross: the door behind them was the way out.', 't_start': 21.0},
    'setting': {
        'preset': 'sky_obby', 'time_of_day': 'sunset', 'lighting': 'warm_key_cool_fill',
        'description': 'Three studded platforms floating over a sea of clouds at sunset.',
        'props': [
            {'id': 'platform_a', 'type': 'platform', 'position': [0.0, 0.3, 0.0], 'size': [2.4, 2.4], 'color': '#4CAF50'},
            {'id': 'platform_b', 'type': 'platform', 'position': [3.0, 0.4, 0.0], 'size': [1.6, 1.6], 'color': '#2196F3'},
            {'id': 'platform_c', 'type': 'platform', 'position': [5.8, 1.0, 0.0], 'size': [2.0, 2.0], 'color': '#FF9800'},
            {'id': 'exit_door', 'type': 'door', 'position': [-0.7, 1.15, 0.0], 'rotation': 90, 'color': '#8E5A2B'},
            {'id': 'flag', 'type': 'checkpoint_flag', 'position': [6.4, 1.7, 0.0], 'color': '#E2504C'},
        ],
    },
    'cast': [{'id': 'hero', 'character_id': 'ch_bloxy'}, {'id': 'pip', 'character_id': 'ch_pip'}],
    'shots': [
        {'id': 's1', 'start_s': 0.0, 'end_s': 3.5, 'camera': {'subject': 'hero', 'framing_start': 'medium',
                                                             'framing_end': 'close_up', 'move': 'push_in', 'side': 'front'}},
        {'id': 's2', 'start_s': 3.5, 'end_s': 7.0, 'camera': {'subject': 'pip', 'framing_start': 'medium_wide',
                                                             'framing_end': 'medium_wide', 'move': 'static', 'side': 'front'}},
        {'id': 's3', 'start_s': 7.0, 'end_s': 12.0, 'camera': {'subject': 'hero', 'framing_start': 'medium_close',
                                                              'framing_end': 'medium', 'move': 'pull_out', 'side': 'front'}},
        {'id': 's4', 'start_s': 12.0, 'end_s': 17.0, 'camera': {'subject': 'hero', 'framing_start': 'full',
                                                               'framing_end': 'full', 'move': 'follow', 'side': 'profile_right'}},
        {'id': 's5', 'start_s': 17.0, 'end_s': 21.0, 'camera': {'subject': 'pip', 'framing_start': 'medium_close',
                                                               'framing_end': 'medium_close', 'move': 'static',
                                                               'side': 'three_quarter_left'}},
        {'id': 's6', 'start_s': 21.0, 'end_s': 22.6, 'camera': {'subject': 'hero', 'framing_start': 'medium',
                                                               'framing_end': 'medium', 'move': 'static', 'side': 'front'}},
        {'id': 's6b', 'start_s': 22.6, 'end_s': 24.0, 'camera': {'subject': 'prop:exit_door', 'framing_start': 'full',
                                                                'framing_end': 'medium_wide', 'move': 'push_in',
                                                                'side': 'profile_left'}},
        {'id': 's6c', 'start_s': 24.0, 'end_s': 25.0, 'camera': {'subject': 'hero', 'framing_start': 'medium',
                                                                'framing_end': 'medium', 'move': 'static', 'side': 'front'}},
        {'id': 's7', 'start_s': 25.0, 'end_s': 30.0, 'camera': {'subject': 'hero', 'framing_start': 'medium_close',
                                                               'framing_end': 'close_up', 'move': 'push_in', 'side': 'front'}},
    ],
    'beats': [
        {'start_s': 0, 'purpose': 'hook', 'description': 'Bloxy jogs up to the edge, confident, then looks down.'},
        {'start_s': 1, 'purpose': 'hook', 'description': 'The next platform is missing. Startled reaction.',
         'continuity': ['Bloxy stands at the right edge of the green platform']},
        {'start_s': 2, 'purpose': 'hook', 'description': 'Hold the startled face; camera pushes in.'},
        {'start_s': 3, 'purpose': 'setup'},
        {'start_s': 4, 'purpose': 'setup', 'description': 'Pip waves from the far orange platform.'},
        {'start_s': 5, 'purpose': 'setup'},
        {'start_s': 6, 'purpose': 'setup'},
        {'start_s': 7, 'purpose': 'escalation', 'description': 'Bloxy peers down into the clouds, worried.'},
        {'start_s': 8, 'purpose': 'escalation'},
        {'start_s': 9, 'purpose': 'escalation'},
        {'start_s': 10, 'purpose': 'escalation', 'description': 'Bloxy steels themself. Determined.'},
        {'start_s': 11, 'purpose': 'escalation'},
        {'start_s': 12, 'purpose': 'climax', 'description': 'Crouch, leap across the gap to the blue platform.'},
        {'start_s': 13, 'purpose': 'climax', 'description': 'Hard landing, knees bend.'},
        {'start_s': 14, 'purpose': 'climax', 'description': 'Wobble on the edge, windmilling arms, recover.'},
        {'start_s': 15, 'purpose': 'reaction', 'description': 'Relief, then a proud fist pump at the camera.'},
        {'start_s': 16, 'purpose': 'reaction'},
        {'start_s': 17, 'purpose': 'reveal', 'description': 'Pip, unimpressed, points back past Bloxy.'},
        {'start_s': 18, 'purpose': 'reveal'},
        {'start_s': 19, 'purpose': 'reveal'},
        {'start_s': 20, 'purpose': 'reveal'},
        {'start_s': 21, 'purpose': 'reveal', 'description': 'Bloxy turns around slowly.'},
        {'start_s': 22, 'purpose': 'reveal', 'description': 'Cut to the exit door, right behind where Bloxy started.',
         'continuity': ['Exit door stands on the green platform behind Bloxy\'s start position']},
        {'start_s': 23, 'purpose': 'reaction', 'description': 'Bloxy turns back to camera.'},
        {'start_s': 24, 'purpose': 'reaction'},
        {'start_s': 25, 'purpose': 'payoff', 'description': 'Facepalm.'},
        {'start_s': 26, 'purpose': 'payoff'},
        {'start_s': 27, 'purpose': 'payoff'},
        {'start_s': 28, 'purpose': 'button', 'description': 'Off-screen Pip: "Again?" Bloxy deadpans to camera.'},
        {'start_s': 29, 'purpose': 'button'},
    ],
    'performance': {
        'hero': [
            _k(0.0, position=[0.6, 0.0], facing=90, expression='curious',
               eye_target={'kind': 'point', 'point': [2.2, 0.2, 0.6]}, head={'pitch': -4}),
            _k(1.0, expression='startled', feet={'weight': 'right'}, shoulders={'raise': -0.3},
               arms={'left': 'chest'}, eye_target={'kind': 'point', 'point': [1.9, 0.1, -1.2]},
               note='Weight onto right foot, shoulders drop, inner brows up, eyes wide at the gap, '
                    'mouth parts; left hand to chest. Hold the reaction.'),
            _k(7.0, expression='worried', head={'pitch': -22}, torso={'lean_forward': 10}, shoulders={'raise': 0.4},
               arms={'left': 'rest'}, feet={'weight': 'center'}, eye_target={'kind': 'point', 'point': [1.8, 0.2, -2.6]}),
            _k(9.8, expression='determined', head={'pitch': 0}, torso={'lean_forward': 0}, shoulders={'raise': 0.0},
               feet={'stance': 'wide'}, eye_target={'kind': 'point', 'point': [3.0, 0.4, 0.3]}),
            _k(14.9, expression='relieved', head={'yaw': -55}, eye_target={'kind': 'camera'},
               feet={'stance': 'neutral'}),
            _k(15.6, expression='proud', arms={'right': 'fist_pump'}),
            _k(16.6, arms={'right': 'rest'}),
            _k(21.0, expression='curious', head={'yaw': 0}, eye_target={'kind': 'character', 'id': 'pip'}),
            _k(22.2, eye_target={'kind': 'prop', 'id': 'exit_door'}),
            _k(24.1, expression='embarrassed', eye_target={'kind': 'camera'}),
            _k(28.8, expression='bored', eye_target={'kind': 'camera'}),
        ],
        'pip': [
            _k(0.0, position=[5.6, 1.0], facing=-90, expression='happy', eye_target={'kind': 'character', 'id': 'hero'}),
            _k(4.0, expression='excited'),
            _k(6.4, expression='happy'),
            _k(12.0, expression='curious'),
            _k(17.2, expression='confused', head={'roll': 8}),
            _k(18.6, eye_target={'kind': 'prop', 'id': 'exit_door'}),
            _k(20.6, expression='smug', head={'roll': 0}, eye_target={'kind': 'character', 'id': 'hero'}),
            _k(28.6, expression='laughing'),
        ],
    },
    'actions': [
        {'character': 'pip', 'type': 'wave', 't': 3.7, 'anticipation_frames': 4, 'main_frames': 30,
         'follow_through_frames': 6, 'params': {'hand': 'left'}},
        {'character': 'hero', 'type': 'talk', 't': 7.6, 'anticipation_frames': 2, 'main_frames': 50,
         'follow_through_frames': 4, 'params': {'hand': 'right'}},
        {'character': 'hero', 'type': 'jump', 't': 12.4, 'anticipation_frames': 8, 'main_frames': 16,
         'follow_through_frames': 8, 'hold_frames': 4, 'params': {'to': [3.0, 0.4]}},
        {'character': 'hero', 'type': 'stumble', 't': 13.9, 'anticipation_frames': 2, 'main_frames': 14,
         'follow_through_frames': 8},
        {'character': 'pip', 'type': 'point', 't': 18.6, 'anticipation_frames': 4, 'main_frames': 10,
         'follow_through_frames': 4, 'hold_frames': 16, 'params': {'hand': 'right'}},
        {'character': 'hero', 'type': 'turn', 't': 21.3, 'anticipation_frames': 4, 'main_frames': 14,
         'follow_through_frames': 6, 'params': {'to_facing': -90}},
        {'character': 'hero', 'type': 'turn', 't': 23.4, 'anticipation_frames': 3, 'main_frames': 12,
         'follow_through_frames': 5, 'params': {'to_facing': 90}},
        {'character': 'hero', 'type': 'facepalm', 't': 25.3, 'anticipation_frames': 4, 'main_frames': 10,
         'follow_through_frames': 6, 'hold_frames': 40, 'params': {'hand': 'right'}},
    ],
    'lines': [
        {'id': 'l1', 'speaker': 'hero', 'text': "Wait... where's the next platform?!", 't': 0.4,
         'emotion': 'startled', 'pace': 'fast', 'volume': 'loud'},
        {'id': 'l2', 'speaker': 'pip', 'text': 'Over here! Just jump!', 't': 4.0, 'emotion': 'excited',
         'pace': 'normal', 'volume': 'loud'},
        {'id': 'l3', 'speaker': 'hero', 'text': "That's way too far!", 't': 7.6, 'emotion': 'worried',
         'pace': 'normal', 'volume': 'normal'},
        {'id': 'l4', 'speaker': 'hero', 'text': 'Okay. You got this.', 't': 10.2, 'emotion': 'determined',
         'pace': 'slow', 'volume': 'soft', 'delivery': 'quietly psyching themself up'},
        {'id': 'l5', 'speaker': 'pip', 'text': "Uh... there's a door right behind you.", 't': 17.4,
         'emotion': 'confused', 'pace': 'normal', 'volume': 'normal', 'delivery': 'deadpan'},
        {'id': 'l6', 'speaker': 'hero', 'text': 'I jumped... for nothing.', 't': 26.0, 'emotion': 'embarrassed',
         'pace': 'slow', 'volume': 'soft'},
        {'id': 'l7', 'speaker': 'pip', 'text': 'Again?', 't': 28.7, 'emotion': 'laughing', 'pace': 'fast',
         'volume': 'normal'},
    ],
    'sfx': [
        {'cue': 'gasp_sting', 't': 1.0}, {'cue': 'whoosh', 't': 12.65}, {'cue': 'thud', 't': 13.2},
        {'cue': 'ding', 't': 22.65}, {'cue': 'fail_horn', 't': 26.9},
    ],
    'music': [{'t': 0, 'cue': 'playful'}, {'t': 7.0, 'cue': 'tension'}, {'t': 13.2, 'cue': 'triumph'},
              {'t': 21.0, 'cue': 'mystery'}, {'t': 25.0, 'cue': 'playful'}],
    'cover_t': 1.4,
    'metadata': {'title': 'The Missing Platform', 'description': 'Bloxy takes the long way. Again.',
                 'tags': ['obby', 'animation', 'funny']},
    'inspiration': {'note': 'Hand-authored demo story; no reference video was used.', 'sources': []},
}


def plan():
    return copy.deepcopy(LAST_PLATFORM)
